version: '3'

services:
  mysqlsrv:
    container_name: project-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqldbproject'
      MYSQL_DATABASE: 'project'
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/MySql:/var/lib/mysql
    networks:
      - project-compose-network

  adminer:
    container_name: project-adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - project-compose-network

  backend:
    container_name: project-java-spring-ws
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8010:8010
    depends_on:
      - mysqlsrv
    networks:
      - project-compose-network
    links:
      - mysqlsrv

  frontend:
    container_name: project-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend

networks:
  project-compose-network:
    driver: bridge
